/*
 * =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
 * DD Poker - Source Code
 * Copyright (c) 2003-2025 Doug Donohoe
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * For the full License text, please see the LICENSE.txt file
 * in the root directory of this project.
 * 
 * The "DD Poker" and "Donohoe Digital" names and logos, as well as any images, 
 * graphics, text, and documentation found in this repository (including but not
 * limited to written documentation, website content, and marketing materials) 
 * are licensed under the Creative Commons Attribution-NonCommercial-NoDerivatives 
 * 4.0 International License (CC BY-NC-ND 4.0). You may not use these assets 
 * without explicit written permission for any uses not covered by this License.
 * For the full License text, please see the LICENSE-CREATIVE-COMMONS.txt file
 * in the root directory of this project.
 * 
 * For inquiries regarding commercial licensing of this source code or 
 * the use of names, logos, images, text, or other assets, please contact 
 * doug [at] donohoe [dot] info.
 * =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
 */
package com.donohoedigital.games.poker;

/** This was generated by /Users/donohoe/work/ddpoker/tools/bin/suitpath.pl - do not modify **/

public class CardSuitPaths
{
    public static final String SPADE = "M125,50C107.5,30,86.748,7.666,85,0c-2.042,7.824-22.501,29.999-40,50c-17.5,20-30,40-30,50c0,30,30,60,60,20c-1.202,20.414-10,60-10,60h40c0,0-8.998-39.723-10-60c30,42.5,60.001,10.104,60-20C155,90,142.5,70,125,50z";

    public static final String CLUB = "M95,125c1.123,20.277,10,55,10,55H65c0,0,8.653-34.586,10-55c0-7.5,0-10-2.5-10c-1.935,0-5,0-7.5,5c-6.316,12.953-10,22.5-30,22.5C13,142.5,0,130,0,100c0-27.5,9-35,25-35s29,6.5,35,12.5c1.933,1.101,5-7.5,5-7.5c-12-8-20-26-20-40c0-9.918,4-30,40-30s40,20,40,30c0,14-8,32-20,40c0,0,3.074,9.426,5,7.5c6-6,19-12.5,35-12.5s25,7,25,35c0,30-13,42.5-35,42.5c-20,0-24.191-10.802-30-22.5c-2.5-5-5.565-5-7.5-5C95,115,95,117.5,95,125z";

    public static final String DIAMOND = "M85,0c0,0-11.407,26.095-30,50C38.751,70.891,15,90,15,90s23.179,18.373,40,40c18.13,23.31,30,50,30,50s11.907-26.738,30-50c16.864-21.683,40-40,40-40s-22.843-17.941-40-40C97.17,27.076,85,0,85,0z";

    public static final String HEART = "M85.138,180c0,0,0-12.245,29.384-58.775c24.048-38.082,58.866-80.719,29.384-110.204c-14.692-14.694-35.681-14.694-48.274,0c-10.494,12.245-9.445,39.184-9.445,39.184h-2.099c0,0,0.865-27.155-9.445-39.184c-12.593-14.694-33.582-14.694-48.274,0c-29.668,29.671,6.705,74.291,29.384,110.204C85.138,167.755,85.138,180,85.138,180z";

    public static final String UNKNOWN = "M68.871,131.604c0-22.333,1.005-30.867,17.526-42.574c9.002-6.381,14.422-10.39,14.422-19.928c0-18.146-8.143-21.481-17.911-21.481c-13.031,0-19.559,8.85-20.474,17.449v0.231H18.776c0-40.479,41.332-65.293,66.69-65.293c27.835,0,65.758,14.812,65.758,60.409c0,18.842-4.033,33.111-21.946,45.906c-10.003,7.212-14.19,8.53-14.19,25.281H68.871zM115.864,179.991H69.492v-32.802h46.372V179.991z";

}
